/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as MetricsIndexImport } from './routes/metrics/index'
import { Route as MetricsDailyImport } from './routes/metrics/daily'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MetricsIndexRoute = MetricsIndexImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRoute,
} as any)

const MetricsDailyRoute = MetricsDailyImport.update({
  id: '/metrics/daily',
  path: '/metrics/daily',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/metrics/daily': {
      id: '/metrics/daily'
      path: '/metrics/daily'
      fullPath: '/metrics/daily'
      preLoaderRoute: typeof MetricsDailyImport
      parentRoute: typeof rootRoute
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/metrics/daily': typeof MetricsDailyRoute
  '/metrics': typeof MetricsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/metrics/daily': typeof MetricsDailyRoute
  '/metrics': typeof MetricsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/metrics/daily': typeof MetricsDailyRoute
  '/metrics/': typeof MetricsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/metrics/daily' | '/metrics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/metrics/daily' | '/metrics'
  id: '__root__' | '/' | '/about' | '/metrics/daily' | '/metrics/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MetricsDailyRoute: typeof MetricsDailyRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MetricsDailyRoute: MetricsDailyRoute,
  MetricsIndexRoute: MetricsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/metrics/daily",
        "/metrics/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/metrics/daily": {
      "filePath": "metrics/daily.tsx"
    },
    "/metrics/": {
      "filePath": "metrics/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
